version: '3.9'

services:
  redis:
    restart: "no"
    image: "redis:alpine"
    hostname: redis
    container_name: redis
    ports:
      - '6379:6379'

  bot:
    restart: "no"
    build:
      dockerfile: Dockerfile
    command: sh -c "python telegram_bot.py"
    container_name: bot

    env_file:
      - ./.env

    volumes:
      - ./:/TG_university
    links:
      - redis
    depends_on:
      - redis
      - celery
      - pg_admin
      - db

  celery:
    restart: "no"
    build: .
    command: celery -A tasks.tasks:celery worker -B -l INFO
    container_name: celery
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - POSTGRES_USER= root
      - POSTGRES_PASSWORD= root
      - POSTGRES_DB= bot_db
    env_file:
      - ./.env
    depends_on:
      - redis
    ports:
      - '5554:5554'

  celery_flower:
    restart: "no"
    build: .
    command: celery -A tasks.tasks:celery flower -l INFO
    container_name: celery_flower
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    env_file:
      - ./.env

    depends_on:
      - redis
    ports:
      - '5555:5555'

  db:
    container_name: pg_db
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bot_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  pg_admin:
    container_name: pg_admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: noemail@noemail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"